# -*- coding: utf-8 -*-
"""API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RQHo5C_RGlF8tqkqlzxIgHGD7Rf7XCNs
"""

import requests
from PIL import Image
from io import BytesIO
from IPython.display import HTML, display

def showPokemonsInfo(resposta):
  resposta = requests.get(url)
  if resposta.status_code == 200:
    info = resposta.json()
    print("ID:", info['id'])
    print("Nom:", info["name"])
    print("Alçada:", info["height"])
    print("Pes:", info["weight"])
    imatge_url = info["sprites"]["other"]["official-artwork"]["front_default"]
    display(Image(url=imatge_url, width=150))
    print("-" * 30)


url_imatge = "https://archives.bulbagarden.net/media/upload/4/4b/Pok%C3%A9dex_logo.png"

#Descarreguem la imatge
info = requests.get(url_imatge)

#Convertim la imatge
img_logo = Image.open(BytesIO(info.content))
html = """<div style="
    display: grid;
    grid-template-columns: repeat(5, 200px);
    gap: 20px;
    ">
    """

#Mostrem
display(HTML(f"""
<div style="text-align:left;">
    <img src="{url_imatge}" width="40%">
</div>
"""))

url = "https://pokeapi.co/api/v2/pokemon?limit=150"
resposta = requests.get(url)

if resposta.status_code == 200:
    dades = resposta.json()

    for pokemon in dades["results"][:50]:  # només 50 per provar

        resposta = requests.get(pokemon["url"])

        if resposta.status_code == 200:
            dades = resposta.json()
            imatge = dades["sprites"]["other"]["official-artwork"]["front_default"]

            '''Lista completa d'amplada
            html += f"""
            <div style="text-align:center;">
                <img src="{imatge}" width="120">
                <p>{dades["name"]}</p>
            </div>
            """
            '''

            html += f"""
            <div style="text-align:center;">
                <img src="{imatge}" width="120">
                <p>{dades["name"]}</p>
            </div>
            """


    html += "</div>"

    display(HTML(html))
else:
    print("Error:", resposta.status_code)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile "/content/drive/MyDrive/Colab Notebooks/utils.py"
# 
# def say_hello():
#     print("Welcome to your Pokedex")